"""Pydantic schemas 聚合。"""

from app.schemas.advisor import (
    AdvisorOut,
    LLMChatRequest,
    LLMEmbeddingRequest,
    LLMMessage,
    MatchedAdvisorOut,
    ScatterPoint,
)
from app.schemas.recruitment import RecruitmentCreateRequest, RecruitmentItem
from app.schemas.resume import ResumeGenerateRequest, ResumeSubmitRequest
from app.schemas.feedback import FeedbackRequest
from app.schemas.qxd import (
    QXDChatRequest,
    QXDMessage,
    SodaAttachment,
    SodaExtension,
)
from app.schemas.governance import (
    GovernedMentorRecord,
    MentorDataset,
    ProvenanceEntry,
    PublicCitation,
    RecordGovernance,
)
from app.schemas.interview import (
    DraftHardConstraint,
    HardConstraint,
    HardConstraintField,
    HardConstraintOperator,
    InterviewAnswerRequest,
    InterviewConfirmRequest,
    InterviewCreateRequest,
    InterviewQuestion,
    InterviewStateResponse,
    StudentPortrait,
    StudentPortraitPatch,
)
from app.schemas.matching import (
    EvidenceClaim,
    MatchExplanation,
    MatchPipelineMeta,
    MatchRequest,
    MatchedMentor,
    OpportunitySignal,
    OpportunitySignalType,
    RankingConfig,
    RankingObjective,
    RankingWeights,
)
from app.schemas.catalog import (
    AdmissionRemark,
    AdvisorEntityType,
    AdvisorOrGroup,
    CatalogCoverage,
    CatalogDataset,
    CatalogFieldEvidence,
    CatalogSnapshot,
    CatalogType,
    Department,
    Offering,
    Program,
    RemarkScope,
    ResearchDirection,
)

__all__ = [
    "AdvisorOut",
    "LLMChatRequest",
    "LLMEmbeddingRequest",
    "LLMMessage",
    "MatchRequest",
    "MatchedAdvisorOut",
    "ScatterPoint",
    "RecruitmentCreateRequest",
    "RecruitmentItem",
    "ResumeGenerateRequest",
    "ResumeSubmitRequest",
    "FeedbackRequest",
    "QXDChatRequest",
    "QXDMessage",
    "SodaAttachment",
    "SodaExtension",
    "GovernedMentorRecord",
    "MentorDataset",
    "ProvenanceEntry",
    "PublicCitation",
    "RecordGovernance",
    "InterviewAnswerRequest",
    "DraftHardConstraint",
    "HardConstraint",
    "HardConstraintField",
    "HardConstraintOperator",
    "InterviewConfirmRequest",
    "InterviewCreateRequest",
    "InterviewQuestion",
    "InterviewStateResponse",
    "StudentPortrait",
    "StudentPortraitPatch",
    "EvidenceClaim",
    "MatchExplanation",
    "MatchPipelineMeta",
    "MatchedMentor",
    "OpportunitySignal",
    "OpportunitySignalType",
    "RankingConfig",
    "RankingObjective",
    "RankingWeights",
    "AdmissionRemark",
    "AdvisorEntityType",
    "AdvisorOrGroup",
    "CatalogCoverage",
    "CatalogDataset",
    "CatalogFieldEvidence",
    "CatalogSnapshot",
    "CatalogType",
    "Department",
    "Offering",
    "Program",
    "RemarkScope",
    "ResearchDirection",
]
