/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvisorCard: typeof import('./components/advisor/AdvisorCard.vue')['default']
    AdvisorDetail: typeof import('./components/advisor/AdvisorDetail.vue')['default']
    AdvisorListPanel: typeof import('./components/advisor/AdvisorListPanel.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppLogo: typeof import('./components/common/AppLogo.vue')['default']
    ChartPanel: typeof import('./components/charts/ChartPanel.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    ChatToolbar: typeof import('./components/chat/ChatToolbar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterBar: typeof import('./components/advisor/FilterBar.vue')['default']
    InterviewProfileCard: typeof import('./components/chat/InterviewProfileCard.vue')['default']
    MiniRadar: typeof import('./components/charts/MiniRadar.vue')['default']
    ProfileForm: typeof import('./components/profile/ProfileForm.vue')['default']
    PublishForm: typeof import('./components/recruitment/PublishForm.vue')['default']
    RadarChartLarge: typeof import('./components/charts/RadarChartLarge.vue')['default']
    RecruitmentList: typeof import('./components/recruitment/RecruitmentList.vue')['default']
    ResumeManager: typeof import('./components/profile/ResumeManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChart: typeof import('./components/charts/ScatterChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
